/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedModeratorRouteImport } from './routes/_authenticated/moderator'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedModeratorIndexRouteImport } from './routes/_authenticated/moderator/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api/webhooks/paddle'
import { Route as AuthenticatedOnboardingStyleProfileRouteImport } from './routes/_authenticated/onboarding/style-profile'
import { Route as AuthenticatedModeratorSupportRouteImport } from './routes/_authenticated/moderator/support'
import { Route as AuthenticatedModeratorModerationRouteImport } from './routes/_authenticated/moderator/moderation'
import { Route as AuthenticatedAdminSubscriptionPlansRouteImport } from './routes/_authenticated/admin/subscription-plans'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAppStyleProfileRouteImport } from './routes/_authenticated/_app/style-profile'
import { Route as AuthenticatedAppPricingRouteImport } from './routes/_authenticated/_app/pricing'
import { Route as AuthenticatedAppPalettesRouteImport } from './routes/_authenticated/_app/palettes'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/_app/history'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated/_app/feed'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppConciergeRouteImport } from './routes/_authenticated/_app/concierge'
import { Route as AuthenticatedAppProfileUserIdRouteImport } from './routes/_authenticated/_app/profile.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModeratorRoute = AuthenticatedModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModeratorIndexRoute =
  AuthenticatedModeratorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModeratorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingStyleProfileRoute =
  AuthenticatedOnboardingStyleProfileRouteImport.update({
    id: '/style-profile',
    path: '/style-profile',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedModeratorSupportRoute =
  AuthenticatedModeratorSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedModeratorRoute,
  } as any)
const AuthenticatedModeratorModerationRoute =
  AuthenticatedModeratorModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedModeratorRoute,
  } as any)
const AuthenticatedAdminSubscriptionPlansRoute =
  AuthenticatedAdminSubscriptionPlansRouteImport.update({
    id: '/subscription-plans',
    path: '/subscription-plans',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppStyleProfileRoute =
  AuthenticatedAppStyleProfileRouteImport.update({
    id: '/style-profile',
    path: '/style-profile',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPricingRoute = AuthenticatedAppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPalettesRoute =
  AuthenticatedAppPalettesRouteImport.update({
    id: '/palettes',
    path: '/palettes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConciergeRoute =
  AuthenticatedAppConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileUserIdRoute =
  AuthenticatedAppProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/moderator': typeof AuthenticatedModeratorRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/concierge': typeof AuthenticatedAppConciergeRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/feed': typeof AuthenticatedAppFeedRoute
  '/history': typeof AuthenticatedAppHistoryRoute
  '/palettes': typeof AuthenticatedAppPalettesRoute
  '/pricing': typeof AuthenticatedAppPricingRoute
  '/style-profile': typeof AuthenticatedAppStyleProfileRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/moderator/moderation': typeof AuthenticatedModeratorModerationRoute
  '/moderator/support': typeof AuthenticatedModeratorSupportRoute
  '/onboarding/style-profile': typeof AuthenticatedOnboardingStyleProfileRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/moderator/': typeof AuthenticatedModeratorIndexRoute
  '/profile/$userId': typeof AuthenticatedAppProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/concierge': typeof AuthenticatedAppConciergeRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/feed': typeof AuthenticatedAppFeedRoute
  '/history': typeof AuthenticatedAppHistoryRoute
  '/palettes': typeof AuthenticatedAppPalettesRoute
  '/pricing': typeof AuthenticatedAppPricingRoute
  '/style-profile': typeof AuthenticatedAppStyleProfileRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/moderator/moderation': typeof AuthenticatedModeratorModerationRoute
  '/moderator/support': typeof AuthenticatedModeratorSupportRoute
  '/onboarding/style-profile': typeof AuthenticatedOnboardingStyleProfileRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/moderator': typeof AuthenticatedModeratorIndexRoute
  '/profile/$userId': typeof AuthenticatedAppProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/moderator': typeof AuthenticatedModeratorRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/_app/concierge': typeof AuthenticatedAppConciergeRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/_app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/_app/palettes': typeof AuthenticatedAppPalettesRoute
  '/_authenticated/_app/pricing': typeof AuthenticatedAppPricingRoute
  '/_authenticated/_app/style-profile': typeof AuthenticatedAppStyleProfileRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/_authenticated/moderator/moderation': typeof AuthenticatedModeratorModerationRoute
  '/_authenticated/moderator/support': typeof AuthenticatedModeratorSupportRoute
  '/_authenticated/onboarding/style-profile': typeof AuthenticatedOnboardingStyleProfileRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/moderator/': typeof AuthenticatedModeratorIndexRoute
  '/_authenticated/_app/profile/$userId': typeof AuthenticatedAppProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/moderator'
    | '/onboarding'
    | '/auth/callback'
    | '/concierge'
    | '/dashboard'
    | '/feed'
    | '/history'
    | '/palettes'
    | '/pricing'
    | '/style-profile'
    | '/admin/members'
    | '/admin/subscription-plans'
    | '/moderator/moderation'
    | '/moderator/support'
    | '/onboarding/style-profile'
    | '/api/webhooks/paddle'
    | '/admin/'
    | '/moderator/'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/auth/callback'
    | '/concierge'
    | '/dashboard'
    | '/feed'
    | '/history'
    | '/palettes'
    | '/pricing'
    | '/style-profile'
    | '/admin/members'
    | '/admin/subscription-plans'
    | '/moderator/moderation'
    | '/moderator/support'
    | '/onboarding/style-profile'
    | '/api/webhooks/paddle'
    | '/admin'
    | '/moderator'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_app'
    | '/_authenticated/admin'
    | '/_authenticated/moderator'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/_authenticated/_app/concierge'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/feed'
    | '/_authenticated/_app/history'
    | '/_authenticated/_app/palettes'
    | '/_authenticated/_app/pricing'
    | '/_authenticated/_app/style-profile'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/subscription-plans'
    | '/_authenticated/moderator/moderation'
    | '/_authenticated/moderator/support'
    | '/_authenticated/onboarding/style-profile'
    | '/api/webhooks/paddle'
    | '/_authenticated/admin/'
    | '/_authenticated/moderator/'
    | '/_authenticated/_app/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderator': {
      id: '/_authenticated/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof AuthenticatedModeratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderator/': {
      id: '/_authenticated/moderator/'
      path: '/'
      fullPath: '/moderator/'
      preLoaderRoute: typeof AuthenticatedModeratorIndexRouteImport
      parentRoute: typeof AuthenticatedModeratorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/style-profile': {
      id: '/_authenticated/onboarding/style-profile'
      path: '/style-profile'
      fullPath: '/onboarding/style-profile'
      preLoaderRoute: typeof AuthenticatedOnboardingStyleProfileRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/moderator/support': {
      id: '/_authenticated/moderator/support'
      path: '/support'
      fullPath: '/moderator/support'
      preLoaderRoute: typeof AuthenticatedModeratorSupportRouteImport
      parentRoute: typeof AuthenticatedModeratorRoute
    }
    '/_authenticated/moderator/moderation': {
      id: '/_authenticated/moderator/moderation'
      path: '/moderation'
      fullPath: '/moderator/moderation'
      preLoaderRoute: typeof AuthenticatedModeratorModerationRouteImport
      parentRoute: typeof AuthenticatedModeratorRoute
    }
    '/_authenticated/admin/subscription-plans': {
      id: '/_authenticated/admin/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/admin/subscription-plans'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_app/style-profile': {
      id: '/_authenticated/_app/style-profile'
      path: '/style-profile'
      fullPath: '/style-profile'
      preLoaderRoute: typeof AuthenticatedAppStyleProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pricing': {
      id: '/_authenticated/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedAppPricingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/palettes': {
      id: '/_authenticated/_app/palettes'
      path: '/palettes'
      fullPath: '/palettes'
      preLoaderRoute: typeof AuthenticatedAppPalettesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/history': {
      id: '/_authenticated/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/feed': {
      id: '/_authenticated/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/concierge': {
      id: '/_authenticated/_app/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedAppConciergeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile/$userId': {
      id: '/_authenticated/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedAppProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppConciergeRoute: typeof AuthenticatedAppConciergeRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppPalettesRoute: typeof AuthenticatedAppPalettesRoute
  AuthenticatedAppPricingRoute: typeof AuthenticatedAppPricingRoute
  AuthenticatedAppStyleProfileRoute: typeof AuthenticatedAppStyleProfileRoute
  AuthenticatedAppProfileUserIdRoute: typeof AuthenticatedAppProfileUserIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppConciergeRoute: AuthenticatedAppConciergeRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppPalettesRoute: AuthenticatedAppPalettesRoute,
  AuthenticatedAppPricingRoute: AuthenticatedAppPricingRoute,
  AuthenticatedAppStyleProfileRoute: AuthenticatedAppStyleProfileRoute,
  AuthenticatedAppProfileUserIdRoute: AuthenticatedAppProfileUserIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminSubscriptionPlansRoute: typeof AuthenticatedAdminSubscriptionPlansRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminSubscriptionPlansRoute:
    AuthenticatedAdminSubscriptionPlansRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedModeratorRouteChildren {
  AuthenticatedModeratorModerationRoute: typeof AuthenticatedModeratorModerationRoute
  AuthenticatedModeratorSupportRoute: typeof AuthenticatedModeratorSupportRoute
  AuthenticatedModeratorIndexRoute: typeof AuthenticatedModeratorIndexRoute
}

const AuthenticatedModeratorRouteChildren: AuthenticatedModeratorRouteChildren =
  {
    AuthenticatedModeratorModerationRoute:
      AuthenticatedModeratorModerationRoute,
    AuthenticatedModeratorSupportRoute: AuthenticatedModeratorSupportRoute,
    AuthenticatedModeratorIndexRoute: AuthenticatedModeratorIndexRoute,
  }

const AuthenticatedModeratorRouteWithChildren =
  AuthenticatedModeratorRoute._addFileChildren(
    AuthenticatedModeratorRouteChildren,
  )

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingStyleProfileRoute: typeof AuthenticatedOnboardingStyleProfileRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingStyleProfileRoute:
      AuthenticatedOnboardingStyleProfileRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedModeratorRoute: typeof AuthenticatedModeratorRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedModeratorRoute: AuthenticatedModeratorRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
