/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api/webhooks/paddle'
import { Route as AuthenticatedOnboardingStyleProfileRouteImport } from './routes/_authenticated/onboarding/style-profile'
import { Route as AuthenticatedAppStyleProfileRouteImport } from './routes/_authenticated/_app/style-profile'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppPricingRouteImport } from './routes/_authenticated/_app/pricing'
import { Route as AuthenticatedAppPalettesRouteImport } from './routes/_authenticated/_app/palettes'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/_app/history'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated/_app/feed'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppConciergeRouteImport } from './routes/_authenticated/_app/concierge'
import { Route as AuthenticatedAppCalibrateRouteImport } from './routes/_authenticated/_app/calibrate'
import { Route as ApiV1ProfileMemberRouteImport } from './routes/api/v1/profile/member'
import { Route as ApiV1PostsFeedRouteImport } from './routes/api/v1/posts/feed'
import { Route as ApiV1PostsCreateRouteImport } from './routes/api/v1/posts/create'
import { Route as ApiV1LookImageRouteImport } from './routes/api/v1/look/image'
import { Route as ApiV1LookGenerateRouteImport } from './routes/api/v1/look/generate'
import { Route as ApiV1ItemsAnalyzeRouteImport } from './routes/api/v1/items/analyze'
import { Route as ApiV1DupesSimilarRouteImport } from './routes/api/v1/dupes/similar'
import { Route as ApiV1ConciergeChatRouteImport } from './routes/api/v1/concierge/chat'
import { Route as ApiV1AnalysisOutfitRouteImport } from './routes/api/v1/analysis/outfit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingStyleProfileRoute =
  AuthenticatedOnboardingStyleProfileRouteImport.update({
    id: '/style-profile',
    path: '/style-profile',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppStyleProfileRoute =
  AuthenticatedAppStyleProfileRouteImport.update({
    id: '/style-profile',
    path: '/style-profile',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPricingRoute = AuthenticatedAppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPalettesRoute =
  AuthenticatedAppPalettesRouteImport.update({
    id: '/palettes',
    path: '/palettes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConciergeRoute =
  AuthenticatedAppConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalibrateRoute =
  AuthenticatedAppCalibrateRouteImport.update({
    id: '/calibrate',
    path: '/calibrate',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiV1ProfileMemberRoute = ApiV1ProfileMemberRouteImport.update({
  id: '/api/v1/profile/member',
  path: '/api/v1/profile/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsFeedRoute = ApiV1PostsFeedRouteImport.update({
  id: '/api/v1/posts/feed',
  path: '/api/v1/posts/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsCreateRoute = ApiV1PostsCreateRouteImport.update({
  id: '/api/v1/posts/create',
  path: '/api/v1/posts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LookImageRoute = ApiV1LookImageRouteImport.update({
  id: '/api/v1/look/image',
  path: '/api/v1/look/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LookGenerateRoute = ApiV1LookGenerateRouteImport.update({
  id: '/api/v1/look/generate',
  path: '/api/v1/look/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ItemsAnalyzeRoute = ApiV1ItemsAnalyzeRouteImport.update({
  id: '/api/v1/items/analyze',
  path: '/api/v1/items/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DupesSimilarRoute = ApiV1DupesSimilarRouteImport.update({
  id: '/api/v1/dupes/similar',
  path: '/api/v1/dupes/similar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConciergeChatRoute = ApiV1ConciergeChatRouteImport.update({
  id: '/api/v1/concierge/chat',
  path: '/api/v1/concierge/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AnalysisOutfitRoute = ApiV1AnalysisOutfitRouteImport.update({
  id: '/api/v1/analysis/outfit',
  path: '/api/v1/analysis/outfit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/calibrate': typeof AuthenticatedAppCalibrateRoute
  '/concierge': typeof AuthenticatedAppConciergeRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/feed': typeof AuthenticatedAppFeedRoute
  '/history': typeof AuthenticatedAppHistoryRoute
  '/palettes': typeof AuthenticatedAppPalettesRoute
  '/pricing': typeof AuthenticatedAppPricingRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/style-profile': typeof AuthenticatedAppStyleProfileRoute
  '/onboarding/style-profile': typeof AuthenticatedOnboardingStyleProfileRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/api/v1/analysis/outfit': typeof ApiV1AnalysisOutfitRoute
  '/api/v1/concierge/chat': typeof ApiV1ConciergeChatRoute
  '/api/v1/dupes/similar': typeof ApiV1DupesSimilarRoute
  '/api/v1/items/analyze': typeof ApiV1ItemsAnalyzeRoute
  '/api/v1/look/generate': typeof ApiV1LookGenerateRoute
  '/api/v1/look/image': typeof ApiV1LookImageRoute
  '/api/v1/posts/create': typeof ApiV1PostsCreateRoute
  '/api/v1/posts/feed': typeof ApiV1PostsFeedRoute
  '/api/v1/profile/member': typeof ApiV1ProfileMemberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/calibrate': typeof AuthenticatedAppCalibrateRoute
  '/concierge': typeof AuthenticatedAppConciergeRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/feed': typeof AuthenticatedAppFeedRoute
  '/history': typeof AuthenticatedAppHistoryRoute
  '/palettes': typeof AuthenticatedAppPalettesRoute
  '/pricing': typeof AuthenticatedAppPricingRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/style-profile': typeof AuthenticatedAppStyleProfileRoute
  '/onboarding/style-profile': typeof AuthenticatedOnboardingStyleProfileRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/api/v1/analysis/outfit': typeof ApiV1AnalysisOutfitRoute
  '/api/v1/concierge/chat': typeof ApiV1ConciergeChatRoute
  '/api/v1/dupes/similar': typeof ApiV1DupesSimilarRoute
  '/api/v1/items/analyze': typeof ApiV1ItemsAnalyzeRoute
  '/api/v1/look/generate': typeof ApiV1LookGenerateRoute
  '/api/v1/look/image': typeof ApiV1LookImageRoute
  '/api/v1/posts/create': typeof ApiV1PostsCreateRoute
  '/api/v1/posts/feed': typeof ApiV1PostsFeedRoute
  '/api/v1/profile/member': typeof ApiV1ProfileMemberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/_app/calibrate': typeof AuthenticatedAppCalibrateRoute
  '/_authenticated/_app/concierge': typeof AuthenticatedAppConciergeRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/_app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/_app/palettes': typeof AuthenticatedAppPalettesRoute
  '/_authenticated/_app/pricing': typeof AuthenticatedAppPricingRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/style-profile': typeof AuthenticatedAppStyleProfileRoute
  '/_authenticated/onboarding/style-profile': typeof AuthenticatedOnboardingStyleProfileRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/api/v1/analysis/outfit': typeof ApiV1AnalysisOutfitRoute
  '/api/v1/concierge/chat': typeof ApiV1ConciergeChatRoute
  '/api/v1/dupes/similar': typeof ApiV1DupesSimilarRoute
  '/api/v1/items/analyze': typeof ApiV1ItemsAnalyzeRoute
  '/api/v1/look/generate': typeof ApiV1LookGenerateRoute
  '/api/v1/look/image': typeof ApiV1LookImageRoute
  '/api/v1/posts/create': typeof ApiV1PostsCreateRoute
  '/api/v1/posts/feed': typeof ApiV1PostsFeedRoute
  '/api/v1/profile/member': typeof ApiV1ProfileMemberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/auth/callback'
    | '/calibrate'
    | '/concierge'
    | '/dashboard'
    | '/feed'
    | '/history'
    | '/palettes'
    | '/pricing'
    | '/profile'
    | '/style-profile'
    | '/onboarding/style-profile'
    | '/api/webhooks/paddle'
    | '/onboarding/'
    | '/api/v1/analysis/outfit'
    | '/api/v1/concierge/chat'
    | '/api/v1/dupes/similar'
    | '/api/v1/items/analyze'
    | '/api/v1/look/generate'
    | '/api/v1/look/image'
    | '/api/v1/posts/create'
    | '/api/v1/posts/feed'
    | '/api/v1/profile/member'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/calibrate'
    | '/concierge'
    | '/dashboard'
    | '/feed'
    | '/history'
    | '/palettes'
    | '/pricing'
    | '/profile'
    | '/style-profile'
    | '/onboarding/style-profile'
    | '/api/webhooks/paddle'
    | '/onboarding'
    | '/api/v1/analysis/outfit'
    | '/api/v1/concierge/chat'
    | '/api/v1/dupes/similar'
    | '/api/v1/items/analyze'
    | '/api/v1/look/generate'
    | '/api/v1/look/image'
    | '/api/v1/posts/create'
    | '/api/v1/posts/feed'
    | '/api/v1/profile/member'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/_authenticated/_app/calibrate'
    | '/_authenticated/_app/concierge'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/feed'
    | '/_authenticated/_app/history'
    | '/_authenticated/_app/palettes'
    | '/_authenticated/_app/pricing'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/style-profile'
    | '/_authenticated/onboarding/style-profile'
    | '/api/webhooks/paddle'
    | '/_authenticated/onboarding/'
    | '/api/v1/analysis/outfit'
    | '/api/v1/concierge/chat'
    | '/api/v1/dupes/similar'
    | '/api/v1/items/analyze'
    | '/api/v1/look/generate'
    | '/api/v1/look/image'
    | '/api/v1/posts/create'
    | '/api/v1/posts/feed'
    | '/api/v1/profile/member'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
  ApiV1AnalysisOutfitRoute: typeof ApiV1AnalysisOutfitRoute
  ApiV1ConciergeChatRoute: typeof ApiV1ConciergeChatRoute
  ApiV1DupesSimilarRoute: typeof ApiV1DupesSimilarRoute
  ApiV1ItemsAnalyzeRoute: typeof ApiV1ItemsAnalyzeRoute
  ApiV1LookGenerateRoute: typeof ApiV1LookGenerateRoute
  ApiV1LookImageRoute: typeof ApiV1LookImageRoute
  ApiV1PostsCreateRoute: typeof ApiV1PostsCreateRoute
  ApiV1PostsFeedRoute: typeof ApiV1PostsFeedRoute
  ApiV1ProfileMemberRoute: typeof ApiV1ProfileMemberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/style-profile': {
      id: '/_authenticated/onboarding/style-profile'
      path: '/style-profile'
      fullPath: '/onboarding/style-profile'
      preLoaderRoute: typeof AuthenticatedOnboardingStyleProfileRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/style-profile': {
      id: '/_authenticated/_app/style-profile'
      path: '/style-profile'
      fullPath: '/style-profile'
      preLoaderRoute: typeof AuthenticatedAppStyleProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pricing': {
      id: '/_authenticated/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedAppPricingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/palettes': {
      id: '/_authenticated/_app/palettes'
      path: '/palettes'
      fullPath: '/palettes'
      preLoaderRoute: typeof AuthenticatedAppPalettesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/history': {
      id: '/_authenticated/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/feed': {
      id: '/_authenticated/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/concierge': {
      id: '/_authenticated/_app/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedAppConciergeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/calibrate': {
      id: '/_authenticated/_app/calibrate'
      path: '/calibrate'
      fullPath: '/calibrate'
      preLoaderRoute: typeof AuthenticatedAppCalibrateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/v1/profile/member': {
      id: '/api/v1/profile/member'
      path: '/api/v1/profile/member'
      fullPath: '/api/v1/profile/member'
      preLoaderRoute: typeof ApiV1ProfileMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/feed': {
      id: '/api/v1/posts/feed'
      path: '/api/v1/posts/feed'
      fullPath: '/api/v1/posts/feed'
      preLoaderRoute: typeof ApiV1PostsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/create': {
      id: '/api/v1/posts/create'
      path: '/api/v1/posts/create'
      fullPath: '/api/v1/posts/create'
      preLoaderRoute: typeof ApiV1PostsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/look/image': {
      id: '/api/v1/look/image'
      path: '/api/v1/look/image'
      fullPath: '/api/v1/look/image'
      preLoaderRoute: typeof ApiV1LookImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/look/generate': {
      id: '/api/v1/look/generate'
      path: '/api/v1/look/generate'
      fullPath: '/api/v1/look/generate'
      preLoaderRoute: typeof ApiV1LookGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/items/analyze': {
      id: '/api/v1/items/analyze'
      path: '/api/v1/items/analyze'
      fullPath: '/api/v1/items/analyze'
      preLoaderRoute: typeof ApiV1ItemsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dupes/similar': {
      id: '/api/v1/dupes/similar'
      path: '/api/v1/dupes/similar'
      fullPath: '/api/v1/dupes/similar'
      preLoaderRoute: typeof ApiV1DupesSimilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/concierge/chat': {
      id: '/api/v1/concierge/chat'
      path: '/api/v1/concierge/chat'
      fullPath: '/api/v1/concierge/chat'
      preLoaderRoute: typeof ApiV1ConciergeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/analysis/outfit': {
      id: '/api/v1/analysis/outfit'
      path: '/api/v1/analysis/outfit'
      fullPath: '/api/v1/analysis/outfit'
      preLoaderRoute: typeof ApiV1AnalysisOutfitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCalibrateRoute: typeof AuthenticatedAppCalibrateRoute
  AuthenticatedAppConciergeRoute: typeof AuthenticatedAppConciergeRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppPalettesRoute: typeof AuthenticatedAppPalettesRoute
  AuthenticatedAppPricingRoute: typeof AuthenticatedAppPricingRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppStyleProfileRoute: typeof AuthenticatedAppStyleProfileRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCalibrateRoute: AuthenticatedAppCalibrateRoute,
  AuthenticatedAppConciergeRoute: AuthenticatedAppConciergeRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppPalettesRoute: AuthenticatedAppPalettesRoute,
  AuthenticatedAppPricingRoute: AuthenticatedAppPricingRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppStyleProfileRoute: AuthenticatedAppStyleProfileRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingStyleProfileRoute: typeof AuthenticatedOnboardingStyleProfileRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingStyleProfileRoute:
      AuthenticatedOnboardingStyleProfileRoute,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
  ApiV1AnalysisOutfitRoute: ApiV1AnalysisOutfitRoute,
  ApiV1ConciergeChatRoute: ApiV1ConciergeChatRoute,
  ApiV1DupesSimilarRoute: ApiV1DupesSimilarRoute,
  ApiV1ItemsAnalyzeRoute: ApiV1ItemsAnalyzeRoute,
  ApiV1LookGenerateRoute: ApiV1LookGenerateRoute,
  ApiV1LookImageRoute: ApiV1LookImageRoute,
  ApiV1PostsCreateRoute: ApiV1PostsCreateRoute,
  ApiV1PostsFeedRoute: ApiV1PostsFeedRoute,
  ApiV1ProfileMemberRoute: ApiV1ProfileMemberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
