import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

/**
 * The embedded admin/moderator/staff suite was removed in favor of the
 * separate MILA_ADMIN app (see the item 9 parity report). routeTree.gen.ts is
 * regenerated by the TanStack Router Vite plugin on every `vite build`/`vite
 * dev`, so this guards against any of those routes silently reappearing.
 */
const routeTree = readFileSync(new URL("./routeTree.gen.ts", import.meta.url), "utf8");

test("the generated route tree has no admin, moderator, or staff routes", () => {
  expect(routeTree).not.toMatch(/fullPath: '\/admin/);
  expect(routeTree).not.toMatch(/fullPath: '\/moderator/);
  expect(routeTree).not.toMatch(/fullPath: '\/staff'/);
  expect(routeTree).not.toContain("routes/admin/");
  expect(routeTree).not.toContain("routes/moderator/");
  expect(routeTree).not.toContain("routes/staff");
});
