-- Every seeded product's affiliate_link was a bare brand homepage, not a real
-- product page (confirmed: they'd all fail scripts/verify-product-links.ts's
-- homepage-path check). Confirmed zero FK references from post_items or
-- user_favorites before deleting — safe, no orphaned rows.
DELETE FROM public.products;

-- Three brands not in the original 6 (Nike, Uniqlo, Muji) needed for the new
-- real catalog. affiliate_network left NULL where no documented program was
-- confirmed during sourcing, rather than guessed.
INSERT INTO public.brands (name, website_url, affiliate_network, status, is_verified_seller) VALUES
  ('Nike', 'https://www.nike.com', 'CJ Affiliate', 'active', true),
  ('Uniqlo', 'https://www.uniqlo.com', NULL, 'active', true),
  ('Muji', 'https://www.muji.us', NULL, 'active', true)
ON CONFLICT DO NOTHING;

-- 50 real, individually-verified products (each affiliate_link was fetched
-- live and confirmed to resolve to a real product page, not a homepage/
-- login/search/account path) across 9 real global brands. Curated manually
-- via web research — no affiliate feed/API was available. Zara, H&M, and
-- Adidas were attempted but fully blocked by bot protection; zero rows from
-- those, not padded with guesses.
--
-- seasonal_palettes intentionally includes the literal broad season word
-- (Spring/Summer/Autumn/Winter) as an array element, not just a fine-grained
-- 16-season label — profiles.color_season is DB-constrained to the broad
-- value only, so matchLookProducts's scoring never fires on fine-grained
-- names alone (confirmed: this was silently broken for all 20 placeholder
-- rows too, which only ever used fine-grained labels).
INSERT INTO public.products
  (brand_id, title, description, image_url, affiliate_link, price, currency, category, gender, body_shapes, seasonal_palettes, in_stock, verification_status, last_verified_at)
VALUES
  -- Reformation
  ((SELECT id FROM public.brands WHERE name = 'Reformation'), 'Ailany Dress', 'Fitted midi dress in muted sage-green viscose georgette, scoop neckline, back smocking, high side slit.', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319572/JADE_GREEN/1319572.1.JADE_GREEN?_s=RAABAB0', 'https://www.thereformation.com/products/ailany-dress/1319572.html', 248.00, 'USD', 'Dresses', 'Female', ARRAY['Hourglass','Pear'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Reformation'), 'Briony Dress', 'Sleeveless deep forest-green maxi dress, halter neckline, fitted bodice, flowing A-line skirt in lightweight georgette.', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1317086/FOREST/1317086.1.FOREST?_s=RAABAB0', 'https://www.thereformation.com/products/briony-dress/1317086.html', 278.00, 'USD', 'Dresses', 'Female', ARRAY['Inverted Triangle','Apple','Rectangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Reformation'), 'Adina Top', 'Short-sleeved cream ditsy-floral top with curved neckline, button front, split hem; organic cotton/ECOVERO viscose blend.', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1320436/DORSET/1320436.1.DORSET?_s=RAABAB0', 'https://www.thereformation.com/products/adina-top/1320436.html', 148.00, 'USD', 'Tops', 'Female', ARRAY['Rectangle','Apple','Hourglass'], ARRAY['Spring'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Reformation'), 'Jeane Skirt', 'Black mid-rise midi skirt with side slit and slim column silhouette, crepe fabric.', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1318790/BLACK/1318790.1.BLACK?_s=RAABAB0', 'https://www.thereformation.com/products/jeane-skirt/1318790.html', 128.00, 'USD', 'Bottoms', 'Female', ARRAY['Rectangle','Pear','Hourglass'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Reformation'), 'Sandy Heeled Sandal', 'Pale blush patent-leather heeled sandal, round block heel, peep toe, adjustable ankle strap.', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1318365/ALABASTER_PATENT/1318365.1.ALABASTER_PATENT?_s=RAABAB0', 'https://www.thereformation.com/products/sandy-heeled-sandal/1318365.html', 248.00, 'USD', 'Shoes', 'Female', ARRAY['Hourglass','Pear','Rectangle'], ARRAY['Spring'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Reformation'), 'Silver Bell Bag', 'Powder-blue crocheted-linen shoulder bag with lace/scalloped edge detailing.', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1320285/CLOUD_BLUE_LINEN/1320285.1.CLOUD_BLUE_LINEN?_s=RAABAB0', 'https://www.thereformation.com/products/silver-bell-bag/1320285.html', 168.00, 'USD', 'Accessories', 'Female', ARRAY['Hourglass','Rectangle','Pear'], ARRAY['Summer'], true, 'verified', now()),

  -- Ganni
  ((SELECT id FROM public.brands WHERE name = 'Ganni'), 'Long-sleeve Top in Double Stripe', 'Slim-fit double-layered top, round neckline, long sleeves, organic cotton/elastane, Strong Blue.', 'https://ganni.kleecks-cdn.com/dw/image/v2/AAWT_PRD/on/demandware.static/-/Sites-ganni-master-catalogue/default/dwd443279b/images/images/model/A1040472_799_2.jpg?sh=2000', 'https://www.ganni.com/us/long-sleeve-top-in-double-stripe-A1040472.html', 215.00, 'USD', 'Tops', 'Female', ARRAY['Rectangle','Hourglass','Inverted Triangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Ganni'), 'Trench Jacket in Double Cotton', 'Black double-breasted organic cotton jacket, curved puff sleeves, hood, two removable waist belts.', 'https://ganni.kleecks-cdn.com/dw/image/v2/AAWT_PRD/on/demandware.static/-/Sites-ganni-master-catalogue/default/dwd66b6573/images/images/model/A1130026_099_2.jpg?sh=2000', 'https://www.ganni.com/us/trench-jacket-in-double-cotton-A1130026.html', 690.00, 'USD', 'Outerwear', 'Female', ARRAY['Rectangle','Apple','Inverted Triangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Ganni'), 'Feminine Buckle Ballerinas in Black', 'Black slingback ballerina flats, pointed toe, two silver-tone buckles, squared block heel.', 'https://ganni.kleecks-cdn.com/on/demandware.static/-/Sites-ganni-master-catalogue/default/dw1baea7b6/images/images/packshots/S2730_4898_099_1.jpg', 'https://www.ganni.com/us/feminine-buckle-ballerinas-in-black-S2730.html', 425.00, 'USD', 'Shoes', 'Female', ARRAY['Hourglass','Pear','Rectangle'], ARRAY['Winter'], true, 'verified', now()),

  -- Nike
  ((SELECT id FROM public.brands WHERE name = 'Nike'), E'Nike Dri-FIT Women''s T-Shirt', 'Recycled polyester Dri-FIT moisture-wicking tee, relaxed classic fit.', 'https://static.nike.com/a/images/t_PDP_144_v1/f_auto,q_auto:eco,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/aefe21db-82a4-44a3-9db4-9712817d40ad/W+NK+DF+RLGD+SS+TEE.png', 'https://www.nike.com/t/dri-fit-womens-t-shirt-dM375qq5', 32.00, 'USD', 'Tops', 'Female', ARRAY['Rectangle','Pear','Apple'], ARRAY['Winter','Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), E'Nike Dri-FIT Legend Men''s Fitness T-Shirt', 'Moisture-wicking Dri-FIT tee, recycled polyester, soft jersey, relaxed fit.', 'https://static.nike.com/a/images/t_PDP_144_v1/f_auto,q_auto:eco/33202c5f-b25f-4439-abca-6182aebc2750/M+NK+DF+TEE+RLGD+RESET.png', 'https://www.nike.com/t/dri-fit-legend-mens-fitness-t-shirt-JmKL0d', 30.00, 'USD', 'Tops', 'Male', ARRAY['Rectangle','Inverted Triangle','Apple'], ARRAY['Winter','Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), E'Nike Air Max 270 Men''s Shoes', 'Lifestyle sneaker, plush Max Air cushioning, breathable textile upper.', 'https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/4e55c3ff-4d4b-4e39-b7ea-40900bf8b2c1/NIKE+AIR+MAX+270.png', 'https://www.nike.com/t/air-max-270-mens-shoes-KkLcGR', 119.97, 'USD', 'Shoes', 'Male', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), E'Nike Air Max 90 Women''s Shoes', 'Textile upper with leather/suede overlays, layered classic look, Nike Air cushioning.', 'https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/64fcfeb6-d406-4906-8696-181050f5ae38/WMNS+AIR+MAX+90.png', 'https://www.nike.com/t/air-max-90-womens-shoes-2ZsM2w', 145.00, 'USD', 'Shoes', 'Female', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), 'Nike Dunk Low Women''s Shoes', 'Basketball-inspired sneaker, crisp leather upper, padded low-cut collar.', 'https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto/ca0fcd7b-6537-4736-8a23-38b6c7104c24/WMNS+NIKE+DUNK+LOW.png', 'https://www.nike.com/t/dunk-low-womens-shoes-ppQwKZ/DD1503-101', 120.00, 'USD', 'Shoes', 'Female', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), E'Nike Sportswear Club Men''s Joggers', 'Midweight brushed fleece jogger, standard fit tapering to ankle.', 'https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/e58e41b0-4f22-4094-9697-b5d1736f9260/M+NK+CLUB+BB+JOGGER.png', 'https://www.nike.com/t/sportswear-club-mens-joggers-UaoROJ9O', 41.97, 'USD', 'Bottoms', 'Male', ARRAY['Rectangle','Inverted Triangle','Apple'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), E'Nike Sportswear Windrunner Men''s Hooded Jacket', 'Lightweight windbreaker, recycled polyester, mesh lining, chevron detailing, roomy fit for layering.', 'https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/b60388a9-b356-4c6c-9728-6e4e860b7598/M+NK+WVN+LND+WR+HD+JKT.png', 'https://www.nike.com/t/sportswear-windrunner-mens-hooded-jacket-5hK13x', 59.97, 'USD', 'Outerwear', 'Male', ARRAY['Rectangle','Inverted Triangle','Apple','Pear'], ARRAY['Autumn','Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Nike'), 'Nike Sportswear Everyday Essential Crew Socks (3 Pairs)', 'Soft stretchy Dri-FIT tech socks, reinforced heel/toe.', 'https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/5e351995-456a-44c6-a74a-0519bb65c988/U+NK+NSW+EVERYDAY+ESSENTIAL+CR.png', 'https://www.nike.com/t/sportswear-everyday-essential-crew-socks-3-pairs-H7K4n7', 16.97, 'USD', 'Accessories', 'Unisex', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Winter'], true, 'verified', now()),

  -- Everlane
  ((SELECT id FROM public.brands WHERE name = 'Everlane'), 'The Essential Organic V-Neck Tee', 'Slim-fit organic cotton tee with a subtle V-neckline.', 'http://www.everlane.com/cdn/shop/files/1d8df405_7254.jpg?v=1753411696', 'https://www.everlane.com/products/mens-essential-organic-v-tee-uniform-white', 34.00, 'USD', 'Tops', 'Male', ARRAY['Rectangle','Inverted Triangle'], ARRAY['Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Everlane'), 'Everyday Shirt in Silky Cotton', 'Relaxed, oversized button-down in silky Supima cotton, cocoon shape, shirttail hem.', 'https://www.everlane.com/cdn/shop/files/8c03c9d4_9b87.jpg?v=1762190882&width=2048', 'https://www.everlane.com/products/womens-everyday-shirt-in-silky-cotton-white', 88.00, 'USD', 'Tops', 'Female', ARRAY['Rectangle','Apple','Pear'], ARRAY['Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Everlane'), 'The Stretch Twill 5-Pocket Pant', 'Medium-weight slim-fit organic cotton twill pant with a touch of elastane.', 'http://www.everlane.com/cdn/shop/files/e1183e51_773b.jpg?v=1755053059', 'https://www.everlane.com/products/mens-stretch-twill-5-pckt-pant-black', 47.00, 'USD', 'Bottoms', 'Male', ARRAY['Rectangle','Inverted Triangle','Hourglass'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Everlane'), 'The Filled Harrington Jacket', 'Lightly padded classic Harrington silhouette, fitted cut, recycled fill.', 'http://www.everlane.com/cdn/shop/files/bcf8b171_532f.jpg?v=1753411674', 'https://www.everlane.com/products/mens-filled-harrington-jckt-black', 119.00, 'USD', 'Outerwear', 'Male', ARRAY['Rectangle','Inverted Triangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Everlane'), 'The Day Sneaker', 'Leather lace-up sneaker, tapered toe, low-ankle height, contrast rubber outsole.', 'http://www.everlane.com/cdn/shop/files/f5eb7274_3d4f.jpg?v=1753411587', 'https://www.everlane.com/products/womens-day-sneaker-white', 44.00, 'USD', 'Shoes', 'Unisex', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Everlane'), 'The Studio Bag', 'Premium leather shoulder bag, adjustable strap, snap closure, 13-inch laptop compartment.', 'http://www.everlane.com/cdn/shop/files/922e9c09_2544.jpg?v=1780966802', 'https://www.everlane.com/products/womens-studio-bag-black', 258.00, 'USD', 'Accessories', 'Unisex', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Winter'], true, 'verified', now()),

  -- COS (prices as displayed live, AED)
  ((SELECT id FROM public.brands WHERE name = 'COS'), 'Ruched Cotton Blouse', 'Regular-fit soft cotton blouse with front pleating/ruching and button closure.', 'https://ae.cos.com/en/media_14c4c6a4cc33592c5c03aee57e4d7c97c24a22a78.avif?width=1200&format=pjpg&optimize=medium', 'https://ae.cos.com/en/buy-ruched-cotton-blouse-grey-dusty-light', 275.00, 'AED', 'Tops', 'Female', ARRAY['Rectangle','Apple','Pear'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'COS'), 'Ribbed Cotton Tank Top', 'Slim-fit ribbed organic cotton tank, rounded neckline, layerable.', 'https://ae.cos.com/en/media_102e12c4aa9ade68a1c13c25d44555288c1f8f5e5.avif?width=1200&format=pjpg&optimize=medium', 'https://ae.cos.com/en/buy-ribbed-cotton-tank-top-black-dark', 90.00, 'AED', 'Tops', 'Unisex', ARRAY['Hourglass','Rectangle','Inverted Triangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'COS'), 'Wool Skirt Trousers', 'Regular-fit trousers in fluid NATIVA wool with a draped skirt-panel wrap at the waist.', 'https://ae.cos.com/en/media_10216a1851c0dd69640e1551613b787581b85dd0f.avif?width=1200&format=pjpg&optimize=medium', 'https://ae.cos.com/en/buy-wool-skirt-trousers-black-dark', 300.00, 'AED', 'Bottoms', 'Female', ARRAY['Pear','Hourglass','Apple'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'COS'), 'Polished-leather Loafers', 'Classic rounded-toe loafer in supple polished black leather with a leather sole.', 'https://ae.cos.com/en/media_1db33bb48f0fd5f8f518808df33315160f9d7ade4.avif?width=1200&format=pjpg&optimize=medium', 'https://ae.cos.com/en/buy-polished-leather-loafers-black-dark', 795.00, 'AED', 'Shoes', 'Unisex', ARRAY['Hourglass','Rectangle','Pear','Inverted Triangle','Apple'], ARRAY['Winter'], true, 'verified', now()),

  -- Uniqlo
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), 'Crew Neck T-Shirt', 'Heavyweight 100% cotton jersey tee, relaxed cut, Uniqlo U collection.', 'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/471583/item/goods_38_471583_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E471583-000/00', 19.90, 'USD', 'Tops', 'Male', ARRAY['Rectangle','Inverted Triangle','Apple'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), 'Rayon Blouse', 'Relaxed-fit rayon-polyester blend blouse with smooth, fluid drape.', 'https://image.uniqlo.com/UQ/ST3/us/imagesgoods/479071/item/usgoods_39_479071_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E479071-000/00', 39.90, 'USD', 'Tops', 'Female', ARRAY['Apple','Rectangle','Pear'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), 'Crew Neck T-Shirt', 'Heavyweight cotton jersey, Uniqlo U, structured collar binding.', 'https://image.uniqlo.com/UQ/ST3/us/imagesgoods/422992/item/usgoods_11_422992_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E422992-000/00', 24.90, 'USD', 'Tops', 'Unisex', ARRAY['Rectangle','Apple','Inverted Triangle'], ARRAY['Spring'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), E'Slim Straight Jeans (Men''s)', 'Vintage-fade denim, slim straight leg.', 'https://image.uniqlo.com/UQ/ST3/us/imagesgoods/485679/item/usgoods_62_485679_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E485679-000/01', 49.90, 'USD', 'Bottoms', 'Male', ARRAY['Rectangle','Inverted Triangle','Hourglass'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), E'Slim Straight Jeans (Women''s)', 'High-waisted slim-fit, straight cut below knee.', 'https://image.uniqlo.com/UQ/ST3/us/imagesgoods/487978/item/usgoods_66_487978_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E487978-000/00', 39.90, 'USD', 'Bottoms', 'Female', ARRAY['Hourglass','Pear','Rectangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), 'Fleece Full-Zip Jacket', 'Dense, springy fleece, machine washable.', 'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/450195/item/goods_12_450195_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E450195-000/00', 49.90, 'USD', 'Outerwear', 'Unisex', ARRAY['Rectangle','Apple','Pear'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Uniqlo'), 'Suede Combination Sneakers', 'Suede/leather-look low-top sneaker.', 'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/471720/item/goods_01_471720_3x4.jpg', 'https://www.uniqlo.com/us/en/products/E471720-000/00', 59.90, 'USD', 'Shoes', 'Unisex', ARRAY['Rectangle','Inverted Triangle','Apple'], ARRAY['Spring'], true, 'verified', now()),

  -- Muji
  ((SELECT id FROM public.brands WHERE name = 'Muji'), 'Cotton Jersey Crewneck T-Shirt', 'Comfortable cotton jersey, relaxed crewneck, neutral/muted colors.', NULL, 'https://www.muji.us/products/cotton-jersey-t-shirt-ab1lg26s', 19.90, 'USD', 'Tops', 'Unisex', ARRAY['Rectangle','Apple','Inverted Triangle'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Muji'), 'UV Protection Waffle T-Shirt', 'Textured waffle weave with built-in sun protection.', NULL, 'https://www.muji.us/products/uv-protection-waffle-t-shirt-ab1pp26s', 29.90, 'USD', 'Tops', 'Unisex', ARRAY['Hourglass','Rectangle','Apple'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Muji'), 'Recycled Cotton Denim Easy Pants', 'Relaxed straight-leg, drawstring waist, recycled cotton denim blend.', NULL, 'https://www.muji.us/products/recycled-cotton-denim-easy-pants-ae12n26a', 49.90, 'USD', 'Bottoms', 'Unisex', ARRAY['Rectangle','Apple','Pear'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Muji'), 'Jersey Tapered Pants', 'Soft stretch recycled poly/rayon/nylon/spandex blend, slim tapered leg.', NULL, 'https://www.muji.us/products/jersey-tapered-pants-ae11e26a', 49.90, 'USD', 'Bottoms', 'Unisex', ARRAY['Rectangle','Inverted Triangle','Hourglass'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Muji'), 'Breathable Jacket', 'Tailored recycled-polyester jacket, lightweight, relaxed breathable silhouette.', NULL, 'https://www.muji.us/products/breathable-jacket-ad0ym26s', 74.99, 'USD', 'Outerwear', 'Unisex', ARRAY['Rectangle','Apple','Pear'], ARRAY['Spring'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Muji'), 'Water Repellent 2-Way Shoulder Bag', 'Water-repellent polyester, crossbody/handbag convertible.', NULL, 'https://www.muji.us/products/water-repellent-2-way-shoulder-bag-efd40a6s', 49.90, 'USD', 'Accessories', 'Unisex', ARRAY['Rectangle','Pear','Hourglass'], ARRAY['Winter'], true, 'verified', now()),

  -- Aritzia
  ((SELECT id FROM public.brands WHERE name = 'Aritzia'), 'Archive Shirt', 'Oversized button-up shirt, dropped shoulders, button cuffs, TENCEL Lyocell twill.', 'https://assets.aritzia.com/image/upload/q_auto,f_auto,dpr_auto,w_1920/f26_a02_116625_34248_on_a', 'https://www.aritzia.com/us/en/product/archive-shirt/116625.html', 98.00, 'USD', 'Tops', 'Female', ARRAY['Rectangle','Apple','Pear'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Aritzia'), 'Falcon Jacket – UnReal Leather', 'Lined bomber, hand pockets, oversized fit, faux-leather.', 'https://assets.aritzia.com/image/upload/q_auto,f_auto,dpr_auto,w_1920/s26_a04_114449_18891_on_a', 'https://www.aritzia.com/us/en/product/falcon-jacket/114449.html', 248.00, 'USD', 'Outerwear', 'Unisex', ARRAY['Rectangle','Pear','Apple'], ARRAY['Autumn'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Aritzia'), 'The Effortless Pant Wider – Crepette', 'Wide-leg trouser, tailored-relaxed silhouette, front knife pleats, Japanese crepe fabric.', 'https://assets.aritzia.com/image/upload/q_auto,f_auto,dpr_auto,w_1920/s25_a06_111478_1274_on_a', 'https://www.aritzia.com/us/en/product/the-effortless-pant%E2%84%A2-wider/111478.html', 103.60, 'USD', 'Bottoms', 'Female', ARRAY['Hourglass','Rectangle','Inverted Triangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Aritzia'), 'G.H.BASS x Aritzia Spence Loafer – Smooth Leather', 'Slip-on round-toe leather loafer, antique-gold coin hardware.', 'https://assets.aritzia.com/image/upload/q_auto,f_auto,dpr_auto,w_1920/s26_n01_131414_1274_on_a', 'https://www.aritzia.com/us/en/product/x-aritzia-spence-loafer/131414.html', 117.00, 'USD', 'Shoes', 'Female', ARRAY['Pear','Hourglass','Rectangle'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Aritzia'), 'Evermore Solid Brass Leather Belt', 'Tie-on belt, solid brass buckle, full-grain leather.', 'https://assets.aritzia.com/image/upload/q_auto,f_auto,dpr_auto,w_1920/f26_n04_131251_1461_on_a', 'https://www.aritzia.com/us/en/product/evermore-solid-brass-leather-belt/131251.html', 88.00, 'USD', 'Accessories', 'Female', ARRAY['Hourglass','Rectangle','Inverted Triangle'], ARRAY['Winter'], true, 'verified', now()),

  -- Net-a-Porter
  ((SELECT id FROM public.brands WHERE name = 'Net-a-Porter'), 'LESET Margo cotton-jersey T-shirt', 'Relaxed-fit crew-neck tee, 100% cotton.', 'https://www.net-a-porter.com/variants/images/19971654707617826/in/w2000_q60.jpg', 'https://www.net-a-porter.com/en-us/shop/product/leset/clothing/t-shirts/margo-cotton-jersey-t-shirt/19971654707617826', 80.00, 'USD', 'Tops', 'Female', ARRAY['Rectangle','Apple','Pear'], ARRAY['Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Net-a-Porter'), 'BOTTEGA VENETA Woven jacket', 'Boxy jacket, pleats, patch pockets, gold-tone knot buttons, cotton/viscose/polyamide blend.', 'https://www.net-a-porter.com/variants/images/46376663162884938/in/w2000_q60.jpg', 'https://www.net-a-porter.com/en-us/shop/product/bottega-veneta/clothing/casual-jackets/woven-jacket/46376663162884938', 3100.00, 'USD', 'Outerwear', 'Unisex', ARRAY['Rectangle','Pear','Apple'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Net-a-Porter'), 'BOTTEGA VENETA Embellished ruched jersey turtleneck maxi dress', 'Body-skimming slinky jersey, turtleneck, ruching, thigh-high split, Knot hardware.', 'https://www.net-a-porter.com/variants/images/46376663162966734/in/w2000_q60.jpg', 'https://www.net-a-porter.com/en-us/shop/product/bottega-veneta/clothing/maxi-dresses/embellished-ruched-jersey-turtleneck-maxi-dress/46376663162966734', 2950.00, 'USD', 'Dresses', 'Female', ARRAY['Hourglass','Rectangle','Pear'], ARRAY['Winter'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Net-a-Porter'), 'CHLOE Swimming Cool patent-leather sandals', 'Sculptural block-wedge thong sandal, leather, A La Plage capsule.', 'https://www.net-a-porter.com/variants/images/46376663163088039/in/w2000_q60.jpg', 'https://www.net-a-porter.com/en-us/shop/product/chloe/shoes/mid-heel/swimming-cool-patent-leather-sandals/46376663163088039', 650.00, 'USD', 'Shoes', 'Female', ARRAY['Pear','Hourglass','Rectangle'], ARRAY['Summer'], true, 'verified', now()),
  ((SELECT id FROM public.brands WHERE name = 'Net-a-Porter'), 'KHAITE Donna Lamb leather clutch', 'East-west silhouette clutch, nappa lambskin, gusseted, Empire hardware.', 'https://www.net-a-porter.com/variants/images/46376663163050843/in/w2000_q60.jpg', 'https://www.net-a-porter.com/en-us/shop/product/khaite/bags/clutch-bags/lamb-leather-clutch/46376663163050843', 2680.00, 'USD', 'Accessories', 'Female', ARRAY['Rectangle','Hourglass','Pear'], ARRAY['Spring'], true, 'verified', now());
